### ISSUE TITLE
Setup GitHub Actions as CronJobs

### ISSUE THREAD

**Issue by VKong6019** [sandboxnu/boba-buddies#31]
tako brought up a great point about leveraging GitHub Actions to automate the Slack Bot. From a glance this seems feasible, but more research can be done. There are a couple things we'll want to integrate with GitHub Actions:
1. Creating new pairs and sending out icebreaker msgs
2. Send out the mid-point check-in message

Here a few resources to look over related to this work:
- https://docs.github.com/en/actions/security-guides/encrypted-secrets
- https://crontab.guru/
- https://dev.to/anshuman_bhardwaj/free-cron-jobs-with-github-actions-31d6
- https://docs.github.com/en/actions/quickstart

**Comment by dfarooq610** [comment]
it would be easiest to have the cron to run on the 1st and 15th of each month
